"""added token support

Revision ID: 254bda36bbe9
Revises: 697e9d533625
Create Date: 2020-03-10 13:49:43.285299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254bda36bbe9'
down_revision = '697e9d533625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token_expiration')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
