"""empty message

Revision ID: 5770af42843a
Revises: 32b688ca419b
Create Date: 2020-02-20 16:50:08.114977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5770af42843a'
down_revision = '32b688ca419b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_user_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('travel_arrangement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['tourist_user.id'], ),
    sa.ForeignKeyConstraint(['travel_arrangement_id'], ['travel_arrangement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guide_user_response')
    # ### end Alembic commands ###
